# Generated by Django 4.1.7 on 2023-03-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
