# Generated by Django 4.1.7 on 2023-03-22 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=100)),
                ('business_number', models.CharField(blank=True, max_length=100)),
                ('billing_address_country', models.CharField(blank=True, max_length=2)),
                ('billing_address_address_l1', models.CharField(blank=True, max_length=100)),
                ('billing_address_address_l2', models.CharField(blank=True, max_length=100)),
                ('billing_address_postal_code', models.CharField(blank=True, max_length=100)),
                ('billing_address_city', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
