# Generated by Django 4.1.7 on 2023-03-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_email_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='odoo_id',
            field=models.IntegerField(default=0),
        ),
    ]
