# Generated by Django 4.1.7 on 2023-05-02 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('base_unit_price', models.FloatField()),
                ('description', models.TextField()),
                ('detailed_type', models.TextField()),
                ('display_name', models.TextField()),
                ('main_picture', models.CharField(max_length=255)),
                ('list_price', models.FloatField()),
                ('name', models.TextField()),
                ('produce_delay', models.FloatField()),
                ('product_tooltip', models.TextField()),
                ('product_type', models.CharField(default='', max_length=128)),
                ('purchase_ok', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('sale_ok', models.BooleanField(default=False)),
                ('qty_available', models.FloatField()),
                ('rating_avg', models.FloatField()),
                ('rating_count', models.IntegerField()),
                ('sale_delay', models.FloatField()),
                ('odoo_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('display_name', models.TextField()),
                ('visibility', models.CharField(max_length=64)),
                ('odoo_id', models.IntegerField(default=0)),
                ('products', models.ManyToManyField(related_name='attributes', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('display_name', models.TextField()),
                ('price_extra', models.FloatField()),
                ('odoo_id', models.IntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.productattribute')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes_values', to='products.product')),
            ],
        ),
    ]
