# Generated by Django 4.1.7 on 2023-05-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='display_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
