# Generated by Django 4.1.7 on 2023-03-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_active_product_is_published_product_odoo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='', max_length=128),
        ),
    ]
