# Generated by Django 4.1.7 on 2023-05-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariant_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='name_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='name_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
