# Generated by Django 4.1.7 on 2023-05-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_description_fr_product_name_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='classic',
            field=models.BooleanField(default=True),
        ),
    ]
